Web portfolio setups
rmjspecial/portfolio-website pull request #1
Opened 2022-04-20 21:57 UTC by rmjspecial

**descriptive pull request**

- I add the index.html file.
- I add the style.css file.
- I used HTML and CSS linter.
- I add gitignore.
- I add a descriptive readme file.

2022-04-20 22:55 UTC, MeqdamAlqudah requested changes
Hi @rmjspecial , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://media3.giphy.com/media/neUaH5fz6ZpefE2KBP/200.webp?cid=ecf05e47avdsnhu4wdtrpl6hrvnh6x67aq7exyv1kp0w2i3r&rid=200.webp&ct=g)
## Highlights
- no linter errors ✅
- Readme file ✅


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-20 22:55 UTC, MeqdamAlqudah commented on index.html
> +    <svg width="18" height="12" viewBox="0 0 18 12" fill="none" xmlns="http://www.w3.org/2000/svg">
- [ ] Please the logo  should  has a link (a tag) to the home page 
![image](https://user-images.githubusercontent.com/74744787/164335187-4631a542-d164-474c-ae60-f7bedcb0f270.png)

2022-04-20 22:55 UTC, MeqdamAlqudah commented on index.html
> +    <svg width="18" height="12" viewBox="0 0 18 12" fill="none" xmlns="http://www.w3.org/2000/svg">
- [ ] Please the hamburger button is on the right and it should have a `nav` tag 

- [ ] Please the hamburger button should have the same margins (top, bottom, left, right) defined in the [design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122)
![image](https://user-images.githubusercontent.com/74744787/164336051-6aec4e84-9fdd-4119-aa38-8560db5c4b50.png)

2022-04-20 22:55 UTC, MeqdamAlqudah commented on index.html
> +  </section>
- [ ] Please the headline section should have the proper background image (decorations are always background images, not `img` tags) i.e use CSS to set the background of the section

| Your design | Figma's |
| ------------- | -------- |
| ![image](https://user-images.githubusercontent.com/74744787/164336323-57d3e53d-f470-4325-a8c2-bb2c37755c8c.png) | ![image](https://user-images.githubusercontent.com/74744787/164336370-78cae29e-8195-4bb9-bc7a-023d2b1290d1.png) |

2022-04-20 22:55 UTC, MeqdamAlqudah commented on index.html
> +      <h2 class="greetings">I’m Rejoice Glad to see you!</h2>
- [ ] Please after changing the logo tag to the link tag please use the `h1` tag for the title here

2022-04-20 22:55 UTC, MeqdamAlqudah commented on index.html
> +          <img src="img/icons/fin.png" alt="fin icon">
- [ ] Please the icons define a list here it is semantically better to use an unordered list tag `ul` to  group them.

2022-04-20 22:55 UTC, MeqdamAlqudah commented on index.html
> +        </span>
- [ ] Please the section should be aligned with flexbox, I know your code is working but the idea of this exercise is to practice flexbox.

2022-04-20 22:55 UTC, MeqdamAlqudah commented on index.html
> +      <h2 class="greetings">I’m Rejoice Glad to see you!</h2>
- [ ] Please make sure that the section uses the font and colors (background and font) defined for the template the font-color here is different than Figma design
![image](https://user-images.githubusercontent.com/74744787/164337620-e5ee0ffc-3396-43e2-b31c-6af11f04c724.png)

2022-04-21 16:39 UTC, KDlamini requested changes
### Hi @ 🙋‍♀️,  

You have done an incredible job implementing some of the changes requested by the previous reviewer. 👏🏾👏🏾👏🏾  
However, there are still some changes that aren't addressed yet. You are almost there! 💪🏾 

![pugReaching](https://user-images.githubusercontent.com/38088818/164508876-52f4155d-9be2-4df0-9e94-688a172e7601.gif)

## Required Changes ♻️
 
**Kindly look through the comments below 👇 for required changes**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

N/A

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-21 16:39 UTC, KDlamini commented on index.html
> +      </a>
![image](https://user-images.githubusercontent.com/38088818/164502209-e37ead24-57fa-48f5-b9fc-20f270cf3c5d.png)
Your `LET’S CONNECT` link is not styled properly. This is because there's an error in the way you named the class `call-to-action-margin-top-12`.

Kindly consider changing it to `class="headline-call margin-top-12"`:
![image](https://user-images.githubusercontent.com/38088818/164503066-e42a8c0a-e584-4f1a-a251-63e78ec0a970.png)
To match your selector in your CSS:
```
.headline-call {
  text-decoration: none;
}

.headline-call h3 {
  text-transform: uppercase;
  color: #7f8cff;
  font-size: 16px;
  font-weight: 500;
  line-height: 24px;
}
```

2022-04-21 16:39 UTC, KDlamini commented on style.css
> +}
The social icons are not sized properly to match the Figma design.
Kindly consider changing the height to `20px` because that is the icons height on the Figma design:
```
.social {
  height: 20px;
}
```

2022-04-21 16:39 UTC, KDlamini commented on style.css
> +}
After the above-mentioned suggestions, your mobile view `navbar`, `LET'S CONNECT` link, and `icons` look a lot more like the Figma design as shown below:
![mobile](https://user-images.githubusercontent.com/38088818/164507877-4da887ad-dc1a-424a-9a16-5fd282338e9e.png)

However, to complete the interface there's still an issue with your background images. I'll leave this one up to you to try and figure out.

2022-04-21 16:53 UTC, KDlamini commented on index.html
> +      <h2 class="greetings">I’m Rejoice Glad to see you!</h2>
Please use an `h1` for the greeting as suggested by the previous reviewer.

2022-04-21 20:08 UTC, rmjspecial commented on style.css
> +}
@KDlamini Thanks for your feedback. Will be grateful if you can assist me to identify the issue with the background :)

2022-04-21 21:07 UTC, rmjspecial commented
hi pls, I have done the necessary update that you stated pls help me check
to see if there are any other changes I need to make as this is my last
review. thanks, I will be grateful to get a quick response from you.

On Thu, Apr 21, 2022 at 5:40 PM Simo Wilson Dlamini <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> Hi @ 🙋‍♀️,
>
> You have done an incredible job implementing some of the changes requested
> by the previous reviewer. 👏🏾👏🏾👏🏾
> However, there are still some changes that aren't addressed yet. You are
> almost there! 💪🏾
>
> [image: pugReaching]
> <https://user-images.githubusercontent.com/38088818/164508876-52f4155d-9be2-4df0-9e94-688a172e7601.gif>
> Required Changes ♻️
>
> *Kindly look through the comments below 👇 for required changes*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> N/A
>
> Cheers 🥂 and Happy coding!!! 👯
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me @KDlamini <https://github.com/KDlamini> in
> your question so I can receive the notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In style.css
> <https://github.com/rmjspecial/portfolio-website/pull/1#discussion_r855336005>
> :
>
> > +.header-nav {
>
> +  background-color: #fff;
>
> +  -webkit-box-align: center;
>
> +  -ms-flex-align: center;
>
> +  align-items: center;
>
> +}
>
> +
>
> +/* Header flex item */
>
> +.header-nav > * {
>
> +  -webkit-box-flex: 1;
>
> +  -ms-flex: 1;
>
> +  flex: 1;
>
> +}
>
> +
>
> +.header-nav span {
>
> +  justify-content: flex-end;
>
> +}
>
>
> Your header logo and hamburger button is still not aligned properly. This
> is because the header-nav selector you used on you CSS does not exist in
> your html. You can resolve that by changing the header-nav to toolbar
> since that's the class name you used for your nav element and the styles
> with be applied.
> Kindly consider adding height: 48px; on line 32 to solve the margin issue
> stated by the previous reviewer.
> Your final CSS should look like this, and your navbar will be perfect:
>
> /* Header flex container */
>
> .toolbar {
>
>   background-color: #fff;
>
>   -webkit-box-align: center;
>
>   -ms-flex-align: center;
>
>   align-items: center;
>
>   height: 48px;
>
> }
>
>
>
> /* Header flex item */
>
> .toolbar > * {
>
>   -webkit-box-flex: 1;
>
>   -ms-flex: 1;
>
>   flex: 1;
>
> }
>
>
>
> .toolbar span {
>
>   justify-content: flex-end;
>
> }
>
>
> ------------------------------
>
> In index.html
> <https://github.com/rmjspecial/portfolio-website/pull/1#discussion_r855370603>
> :
>
> > +      <a href="#" class="call-to-action-margin-top-12">
>
> +        <h3>LET’S CONNECT</h3>
>
> +      </a>
>
>
> [image: image]
> <https://user-images.githubusercontent.com/38088818/164502209-e37ead24-57fa-48f5-b9fc-20f270cf3c5d.png>
> Your LET’S CONNECT link is not styled properly. This is because there's
> an error in the way you named the class call-to-action-margin-top-12.
>
> Kindly consider changing it to class="headline-call margin-top-12":
> [image: image]
> <https://user-images.githubusercontent.com/38088818/164503066-e42a8c0a-e584-4f1a-a251-63e78ec0a970.png>
> To match your selector in your CSS:
>
> .headline-call {
>
>   text-decoration: none;
>
> }
>
>
>
> .headline-call h3 {
>
>   text-transform: uppercase;
>
>   color: #7f8cff;
>
>   font-size: 16px;
>
>   font-weight: 500;
>
>   line-height: 24px;
>
> }
>
>
> ------------------------------
>
> In style.css
> <https://github.com/rmjspecial/portfolio-website/pull/1#discussion_r855374911>
> :
>
> > +.social {
>
> +  height: 25px;
>
> +}
>
>
> The social icons are not sized properly to match the Figma design.
> Kindly consider changing the height to 20px because that is the icons
> height on the Figma design:
>
> .social {
>
>   height: 20px;
>
> }
>
>
> ------------------------------
>
> In style.css
> <https://github.com/rmjspecial/portfolio-website/pull/1#discussion_r855381308>
> :
>
> > +.headline {
>
> +  background-image: url(../portfolio-website/img/header-background-mobile.png);
>
> +  background-repeat: no-repeat;
>
> +  background-size: cover;
>
> +  background-position: 0 bottom;
>
> +}
>
> +
>
> +/* Headline flex container */
>
> +.headline-wrap {
>
> +  background-image: url(../portfolio-website/img/background-img.png);
>
> +  background-size: cover;
>
> +  padding: 114px 24px 136px 24px;
>
> +  -webkit-box-orient: vertical;
>
> +  -webkit-box-direction: normal;
>
> +  -ms-flex-direction: column;
>
> +  flex-direction: column;
>
> +}
>
>
> After the above-mentioned suggestions, your mobile view navbar, LET'S
> CONNECT link, and icons look a lot more like the Figma design as shown
> below:
> [image: mobile]
> <https://user-images.githubusercontent.com/38088818/164507877-4da887ad-dc1a-424a-9a16-5fd282338e9e.png>
>
> However, to complete the interface there's still an issue with your
> background images. I'll leave this one up to you to try and figure out.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rmjspecial/portfolio-website/pull/1#pullrequestreview-948842409>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWQADVMFTES7CQIAKSX5MFLVGGAGTANCNFSM5T5L4DKA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-04-21 23:07 UTC, KDlamini commented
> hi pls, I have done the necessary update that you stated pls help me check to see if there are any other changes I need to make as this is my last review. thanks, I will be grateful to get a quick response from you.

Hi @rmjspecial,
Great work making the changes. 👏🏾
I still cannot see the background on my side. But if you say it shows correctly on your browser, perhaps there's something wrong on my side. Otherwise, everything looks good. You can submit it for a re-review.

2022-04-21 23:09 UTC, rmjspecial commented
> > hi pls, I have done the necessary update that you stated pls help me check to see if there are any other changes I need to make as this is my last review. thanks, I will be grateful to get a quick response from you.
> 
> Hi @rmjspecial, Great work making the changes. 👏🏾 I still cannot see the background on my side. But if you say it shows correctly on your browser, perhaps there's something wrong on my side. Otherwise, everything looks good. You can submit it for a re-review.

Ok thanks but do you feel there is anything else i should do now that the background is not showing on your end i just hope the next reviewer won't face same issue.

2022-04-21 23:11 UTC, rmjspecial commented
> > > hi pls, I have done the necessary update that you stated pls help me check to see if there are any other changes I need to make as this is my last review. thanks, I will be grateful to get a quick response from you.
> > 
> > 
> > Hi @rmjspecial, Great work making the changes. 👏🏾 I still cannot see the background on my side. But if you say it shows correctly on your browser, perhaps there's something wrong on my side. Otherwise, everything looks good. You can submit it for a re-review.
> 
> Ok thanks but do you feel there is anything else i should do now that the background is not showing on your end i just hope the next reviewer won't face same issue.

Or is it possible you get to review the code again since you already know the in and out of everything. Thanks for await your kind response.

2022-04-22 07:09 UTC, KDlamini commented
> > > > hi pls, I have done the necessary update that you stated pls help me check to see if there are any other changes I need to make as this is my last review. thanks, I will be grateful to get a quick response from you.
> > > 
> > > 
> > > Hi @rmjspecial, Great work making the changes. 👏🏾 I still cannot see the background on my side. But if you say it shows correctly on your browser, perhaps there's something wrong on my side. Otherwise, everything looks good. You can submit it for a re-review.
> > 
> > 
> > Ok thanks but do you feel there is anything else I should do now that the background is not showing on your end I just hope the next reviewer won't face the same issue.
> 
> Or is it possible you get to review the code again since you already know the in and out of everything. Thanks for awaiting your kind response.

Hi @rmjspecial,
Sorry for the late reply, it was quite very late for me when you made a comment.
I have already re-reviewed your code because I understand that this is your last review. Your mobile view now meets all the requirements with the exception of the background not showing. 🤗 

Take advantage of the morning session, coding partners, and stand-up session to share your code and perform peer reviews on each other. The point of Microverse is to help you learn how to use different ways to debug code whether that would be through peer reviews, YouTube tutorials, Google searches, or personal skills. Trust me if you spend a little more time debugging the background issue you'll learn some interesting methods to apply background images. When you finally solve it you will always remember how to do it properly next time. If I give you all the answers, I will be robbing you of the opportunity to learn and grow.

Good luck and happy coding 🥂

2022-04-22 07:12 UTC, m05e5 approved these changes
# Hi @rmjspecial , 

### Status: Approved ✔️
![goodjob](https://user-images.githubusercontent.com/60631456/130260474-3c2d5e5c-96df-43de-a0db-8d0059c10862.gif)


:+1: You have done all the required changes asked by the previous reviewer. Well Done.

Your project is complete!  There are some optional changes I've suggested to you to make your project best, other than that nothing else to say.
Congratulations! 🎉 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

[Highly Recommended]
- _( optional )_ Hi. Great job. Please as mentioned in the requirements, the logo should be in the header, but out of the nav

- _( optional )_ I tried inspecting your code and I can see you actually have the background image being called but its not on the there on the layout. So, either there's a problem with the import URL, or the problem is with the image itself. I recommend checking it again before continuing with the other projects

_Apart from that you really did a great job_ 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
-----

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_m05e5_**

------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 07:12 UTC, m05e5 commented on index.html
> +      <a href="#" class="logo">view</a>
- _(optional)_ Hi. Great job. Please as mentioned in the requirements, the logo should be in the header, but out of the nav

2022-04-22 07:53 UTC, merged

2022-04-22 16:22 UTC, rmjspecial commented
hi, thanks for the kind review I will see to the changes.

On Fri, Apr 22, 2022 at 8:09 AM Simo Wilson Dlamini <
***@***.***> wrote:

> hi pls, I have done the necessary update that you stated pls help me check
> to see if there are any other changes I need to make as this is my last
> review. thanks, I will be grateful to get a quick response from you.
>
> Hi @rmjspecial <https://github.com/rmjspecial>, Great work making the
> changes. 👏🏾 I still cannot see the background on my side. But if you say
> it shows correctly on your browser, perhaps there's something wrong on my
> side. Otherwise, everything looks good. You can submit it for a re-review.
>
> Ok thanks but do you feel there is anything else I should do now that the
> background is not showing on your end I just hope the next reviewer won't
> face the same issue.
>
> Or is it possible you get to review the code again since you already know
> the in and out of everything. Thanks for awaiting your kind response.
>
> Hi @rmjspecial <https://github.com/rmjspecial>,
> Sorry for the late reply, it was quite very late for me when you made a
> comment.
> I have already re-reviewed your code because I understand that this is
> your last review. Your mobile view now meets all the requirements with the
> exception of the background not showing. 🤗
>
> Take advantage of the morning session, coding partners, and stand-up
> session to share your code and perform peer reviews on each other. The
> point of Microverse is to help you learn how to use different ways to debug
> code whether that would be through peer reviews, YouTube tutorials, Google
> searches, or personal skills. Trust me if you spend a little more time
> debugging the background issue you'll learn some interesting methods to
> apply background images. When you finally solve it you will always remember
> how to do it properly next time. If I give you all the answers, I will be
> robbing you of the opportunity to learn and grow.
>
> Good luck and happy coding 🥂
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rmjspecial/portfolio-website/pull/1#issuecomment-1106082194>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWQADVJ27UZITUGOBYXQSLDVGJGB7ANCNFSM5T5L4DKA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>